### ISSUE TITLE
Broken in Python 3

### ISSUE THREAD

**Issue by andrew-azarov** [vinlyx/mgzip#11]
Leaves the threads hanging forever hitting thread limit per proc on freebsd

Traceback (most recent call last):
  File "create_dedup.py", line 55, in <module>
    with mgzip.open(location,'wb',thread=4,blocksize=SZ//4, compresslevel=3) as block:
  File "/usr/local/lib/python3.7/site-packages/mgzip/multiProcGzip.py", line 55, in open
    binary_file = MultiGzipFile(filename, gz_mode, compresslevel, thread=thread, blocksize=blocksize)
  File "/usr/local/lib/python3.7/site-packages/mgzip/multiProcGzip.py", line 174, in __init__
    self.pool = Pool(self.thread)
  File "/usr/local/lib/python3.7/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/usr/local/lib/python3.7/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/local/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by timhughes** [comment]
Fixed in fork https://github.com/pgzip/pgzip/pull/1
